### ISSUE TITLE
Propose to abandon other loggers than FluentLogger

### ISSUE THREAD

**Issue by DQNEO** [fluent/fluent-logger-php#36] opened 2015-04-25 13:30 UTC
First, thank you for creating great softwares Fluentd and fluent-logger-php.
They are both amazing and helped us to improve our web infrastructures a lot.

Well, I hear Fluentd is a kind of Unix pipe on the web infrastructure and the design looks to be influenced by the Unix philosophy.  **Do one thing and do it well** 

But this project looks to have 2 roles.
* a logger to send logs to a Fluentd daemon
* a bridge to send logs to multiple facilities (File, HTTP, Console)

As for the second function,  [Monolog](https://github.com/Seldaek/monolog) has become a de-facto standard in the modern PHP world.

If we focused on the first role,  we could remove many class files and make the project much simpler, thinner, and more readable.
For example, see the perl counterpart [fluent-logger-perl](https://github.com/fluent/fluent-logger-perl/tree/master/lib/Fluent). It has only one pm file so it's very easy to read.

So my proposition is to focus on sending logs only to Fluentd  and forget about File ,HTTP, Console etc.
As a reference implementation, I created a project called `fluent-simplelogger`
https://github.com/DQNEO/php-fluent-simplelogger/tree/master/src

## Pros
* easy to read and understand
* easy to maintain
* less bugs, less issues

## Cons
* breaks backward compatibility ( requires a major version change)

If you are welcome to accept it , I will send a Pull Request.

Thanks again for such a nice library.

**Comment by sasezaki** [comment] 2015-04-29 13:08
@DQNEO 
You are mixing Handler/Writer/Sender & log level client (eg. psr-3, monolog, Zed\Log, PEAR's Log)

I don't objection for removing `ChainLogger`, `FileLogger` & `ConsoleLogger`.
But at least, NullLogger  (implements LoggerInterface)  is required for stub.

IMHO, `Fluent\Logger` should be renamed to `Sender` ( `fluent-logger-java` & `fluent-logger-python` already named it as that)

**Comment by DQNEO** [comment] 2015-04-29 14:13
@sasezaki  Thank you for the comment.

>  You are mixing Handler/Writer/Sender & log level client (eg. psr-3, monolog, Zed\Log, PEAR's Log)

OK, I am Sorry for my lack of knowledge.

> I don't objection for removing ChainLogger, FileLogger & ConsoleLogger.
> But at least, NullLogger (implements LoggerInterface) is required for stub.

Sounds reasonable. Then how about `HttpLogger` ?

> IMHO, Fluent\Logger should be renamed to Sender ( fluent-logger-java & fluent-logger-python already named it as that)

The name `Sender` is not bad, but it seems to be a matter of personal taste. 
(e.g. In perl, the name is `Logger`.)
Besides, if we changed the namespace or classname, users would get confused.

My proposition is to eliminate things.
Renaming is another issue.

**Comment by sasezaki** [comment] 2015-05-01 14:20
` for my lack of knowledge.`
NO! this confusion is caused by bad naming. So I suggested renaming ;-)

**Comment by DQNEO** [comment] 2015-05-02 09:07
Now that I am given the permission to commit this project,  I can think this proposal is accepted.

**Comment by sasezaki** [comment] 2015-05-02 10:50
I can't believe your behavior.
Is this personal project ? Are you perfect man ? Are you try change everything without RFC ?

**Comment by DQNEO** [comment] 2015-05-02 11:43
@sasezaki  
Thank you for the comment.

> Is this personal project ? Are you perfect man ? 

Off course not.
The maintainers delegated me to manage this project.
So I though I can decide the direction of the project.

If  I broke any written rules or guide lines ,  I would apology.
Could you show me which rules did I break ?

Honestly, I have little experiences of managing OSS libraries with many users.
So I would like you to show me concretely which of my behaviors you disliked.

> Are you try change everything without RFC ?

No. Off course I plan to make PRs before changing things, especially important changes which will break B.C. 
I did not remove any class files yet , did I?

If you have an opinion on the management of  this project, you can propose rules or If you think you can manage it better than me, you can request a admin right.

Discussion are welcome.

**Comment by sasezaki** [comment] 2015-05-02 13:40
I just mentioned about `closed this issue` with commet " I can think this proposal is accepted."

**Comment by DQNEO** [comment] 2015-05-02 14:12
OK, I reopen it.

**Comment by sasezaki** [comment] 2015-05-02 15:07
> I did not remove any class files yet ,

Yeah, so this issue can't be closed. "plan" does not fix anything .

**Closed** 2015-10-16 01:43 UTC
